version: '2'
services:
  ctomcat:
    build:
      context: .
      dockerfile: ./docker/tomcat/Dockerfile
    ports:
      - "8082:8080"
      - "18001:18000"
    image: itomcat-attendance:1.0
    env_file:
      - ./config.env
     
  cpostgres:
    build:
      context: "./docker/postgres"
    restart: always
    image: ipostgres-attendance
    ports:
      - 5431:5432
