version: '2'
services:
  ctomcat:
    build:
      context: .
      dockerfile: ./docker/tomcat/Dockerfile
    ports:
      - "8080:8080"
    image: itomcat-demo:1.0
    env_file:
      - ./config.env
     
  cpostgres:
    build:
      context: "./docker/postgres"
    restart: always
    image: ipostgres-demo
    ports:
      - 5432:5432
